test:
    windows_live:
      appid: your_app_id
      secret: your_app_secret_key
      security_algorithm: wsignin1.0
      return_url: http://yourserver.com/your_return_url
      policy_url: http://yourserver.com/you_policy_url

    yahoo:
      consumer_key: dj0yJmk9OHZQdlZwTjFwb0hkJmQ9WVdrOWRYTm5kbEo1TjJjbWNHbzlNalUwTnpVME16WXkmcz1jb25zdW1lcnNlY3JldCZ4PTRk
      consumer_secret: 946386fea72817353c03b30fb0feb95431af6882
  
    google:
        consumer_key: browser.zen.turingstudio.com
        consumer_secret: R94k7Wo+W2oQEo1CwLO4cv3w