test:
    windows_live:
      application_id: app_id
      secret_key: your_secret
      privacy_policy_url: http://yourserver.com/you_policy_url

    yahoo:
        consumer_key: your_key
        consumer_secret: your_secret_key
  
    google:
        consumer_key: your_key
        consumer_secret: your_secret_key